name: Build

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        autofac: ['lowestSupported', '6.0.0']
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v1
    - name: Restore dependencies
      run: dotnet restore -property:AutofacVersion=${{matrix.autofac}}
    - name: Build
      run: dotnet build --no-restore
    - name: Run Tests
      run: dotnet test --no-restore --verbosity normal
